### PR TITLE
Closely match top level body to spec (fixes #28)

### LINKED ISSUE #28: Regression: "Allow annotations ..." started to cause failures for citeproc-py
I believe (through manual bisection) that it was d1bd9b26f024d66d2fc9cbda69a2448af84d86cd (" Allow annotations on top-level body") included in 2.6.2 which introduced a regression which causes citeproc-py failures (https://github.com/brechtm/citeproc-py/issues/94).

edit: this is the rnc file - -https://github.com/citation-style-language/schema/blob/e295d632a7548470457761d63cb9dad561afa84d/csl.rnc

### PR DESCRIPTION
**Pull request by djc**
@yarikoptic can you check if this solves the problem for you?

### CODE REVIEW

**Comment by djc** [comment]
@yarikoptic ping?

**Comment by yarikoptic** [comment]
Thanks for the ping.  Yes, with this PR there is no crash and produced rng is identical to the one with 2.6.1

**Comment by djc** [comment]
Alright, I've uploaded 2.6.3 to PyPI. Thanks for testing!

**Comment by djc** [comment]
(Sorry, uploaded the wrong thing -- you should use 2.6.4.)

**Pull request merged**
