### PR TITLE
Drop (untested and long long gone) 2.6, add 3.9 and missing specs for other pythons

### PR DESCRIPTION
**Pull request by yarikoptic**
observed some odd installation error claimed for rnc2rng (3.9 was ok actually) for citeproc-py, decided to pick here and tune things up

### CODE REVIEW

**Comment by djc** [comment]
Thanks!

**Comment by yarikoptic** [comment]
I am confused though -- there were no tick back from CI here, and I don't see build anywhere on https://travis-ci.org/github/djc/rnc2rng/builds .  I wonder if relates to master-vs-main: PR was against `main`. Builds on Travis seems to be for master

**Comment by djc** [comment]
This project is now using GitHub Actions instead of Travis, so that would explain why there aren't any new Travis builds?

**Comment by djc** [comment]
Ah, it looks like I failed to configure GitHub Actions to trigger on pull requests. Should be fixed now.

**Comment by yarikoptic** [comment]
Readme should then adjust to use another badge.

**Comment by djc** [comment]
Fair point, done.

**Pull request merged**
