### PR TITLE
Fix annotation and namespace issue (continued)

### LINKED ISSUE #16: Parsing of documented groups fails
e.g.

```
element foo {
	## documentation
	(
		attribute a {xsd:string},
		attribute b {xsd:string}
	)?
}
```

Will fail to parse, giving the error
parse error in test.rnc [3:2]

This is, as far as I can tell, legal syntax: 
https://www.oasis-open.org/committees/relax-ng/compact-20021121.html §5.2 says

> \## comments can only be used immediately before before a pattern, nameClass, grammarContent or includeContent. Multiple ## comments are allowed. Multiple adjacent ## comments without any intervening blank lines are merged into a single documentation element. Any ## comments must precede any annotation in square brackets.

And parenthesized patterns are still patterns per the syntax in §2

> pattern ::= ... "(" pattern ")

I **think** (not completely confident that I've mapped how you're naming the productions vs what that spec uses) that the issue is just at https://github.com/djc/rnc2rng/blob/2b2c3c7c7f6a59055e68aea53769028609b469e9/rnc2rng/parser.py#L394-L401

And specifically that the fist rule should have been for primary, not annoated-primary, e.g. 
```diff
-@pg.production('annotated-primary : LPAREN pattern RPAREN')
+@pg.production('primary : LPAREN pattern RPAREN')
```

Thus still allowing the next production to attach annotations in front of such a group.

That change does make the grammar where I first encountered the issue parse and agree with how trang translates this constract to rng (i.e. something like the following, though your translation is more eager about using a child `<name ns="...">` element, whereas trang prefers to use a [name attribute which is transformed to this form](https://relaxng.org/spec-20011203.html#IDAEAZR). I don't think that causes any real difference in semantics though.

```xml
    <element name="foo">
      <optional>
        <group>
          <a:documentation>documentation</a:documentation>
          <attribute name="a">
            <data type="string"/>
          </attribute>
          <attribute name="b">
            <data type="string"/>
          </attribute>
        </group>
      </optional>
    </element>
```

rnc2rng also seems to parse, but not emit, documentation elements for references, e.g. 

```
ref = element bar { empty }

start = element foo {
	## documentation
	ref
}
```

emits

```xml
<grammar xmlns="http://relaxng.org/ns/structure/1.0">
  <define name="ref">
    <element>
      <name ns="">bar</name>
      <empty/>
    </element>
  </define>
  <start>
    <element>
      <name ns="">foo</name>
      <ref name="ref"/>
    </element>
  </start>
</grammar>
```
instead of trang's

```xml
<grammar xmlns:a="http://relaxng.org/ns/compatibility/annotations/1.0" xmlns="http://relaxng.org/ns/structure/1.0">
  <define name="ref">
    <element name="bar">
      <empty/>
    </element>
  </define>
  <start>
    <element name="foo">
      <ref name="ref">
        <a:documentation>documentation</a:documentation>
      </ref>
    </element>
  </start>
</grammar>
```

i.e. the `<a:documentation>` for the ref is missing. I haven't figured out where this is going wrong, so I don't know if it's truly related or should be a separate issue.

### PR DESCRIPTION
**Pull request by jombr**
Continue the work of #19 to fix #16

>Fixes #16, and a variety of other issues hit in processing my existing grammars to extract documentation
>
>  - Support documentation (or any other annotations) on groups and references to a named define
>  - use a: as the xmlns prefix for http://relaxng.org/ns/compatibility/annotations/1.0, but don't assume that the user has already defined it, and make sure to qualify the case where they defined namespace a=... to be something else too.
>  - Follow the spec for whitespace handling in a:documentation
>  - Fix combining |=, &= productions in the presence of annotations.
>  - Fix handling of datatag and literals with possibly-namespaced type references.

Additional changes:
 - Re-based onto latest master
 - Resolved #19 review style nit comments https://github.com/djc/rnc2rng/pull/19#pullrequestreview-293522561
 - Implemented grammar level datatypeLibrary solution from https://github.com/djc/rnc2rng/pull/19#issuecomment-535790411

## grammar level datatypeLibrary solution
 - a grammar-level `datatypeLibrary="http://www.w3.org/2001/XMLSchema-datatypes"` gets printed if `xsd:*` was ever referenced
 - Any datatypes != http://www.w3.org/2001/XMLSchema-datatypes written explicitly on `<data>` or `<value>`
 - Include grammar root assert removed (one that tries to verify the grammar level datatypes are the same)

## Changes in addition to discussed solution
 - Capture datatypes from included grammar so the prefix can be looked up and included on explicit written custom datatypes

### CODE REVIEW

**Comment by djc** [comment]
Do you want to take over maintenance?

https://github.com/djc/rnc2rng/issues/41

**Comment by jombr** [comment]
> Do you want to take over maintenance?
> 
> #41

I'm willing to but there may be quite a bit with the code base, Continuous Integration, and Deployment to PiPy that I'm not familiar with. That and I started learning Python this year while only visiting relaxng off and on.

That being said I'm interested, enjoy learning, and the package seems pretty stable. If your comfortable with that and can be available for questions then I'll do it.

**Comment by djc** [comment]
I've invited you as a collaborator on this repository. Let's see how this works out? Since you're indicating that you're pretty new to things I'll withhold PyPI permissions for now -- feel free to ask questions.

**Comment by jombr** [comment]
> I've invited you as a collaborator on this repository. Let's see how this works out? Since you're indicating that you're pretty new to things I'll withhold PyPI permissions for now -- feel free to ask questions.

Alright! I have some reading to do.

Let me know if this PR works for you (If you think its aligned with what @puetzk had in mind).

If this PR checks out I'll probably re-base it after #45 lands.

**Comment by djc** [comment]
Sorry, I won't have time to thoroughly review this PR -- happy to answer any specific questions you have, though!

**Comment by jombr** [comment]
No worries, figured it could be rude if I pushed without asking for a review. I'll review it again before merging.

**Comment by djc** [comment]
Not rude, I'm considering you the primary maintainer from here on, though I'll still want to check before we publish to PyPI.

**Pull request merged**
