### PR TITLE
ENH(CI): add testing on windows

### PR DESCRIPTION
**Pull request by yarikoptic**
Required minor refactoring to avoid posixy specification of
env variable -- the rest should be ok AFAIK

Inspired by @rly's #31

### CODE REVIEW

**Comment by djc** [comment]
I don't see any actual changes here, only in CI -- is that intended?

**Comment by yarikoptic** [comment]
yes -- the whole point is to add CI run on windows, no changes to code.  But I guess actions are configured not to run from forks to avoid leaking the secret... not sure if you actually even need dedicated COVERALLS token for public repo - should work with
```
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Review by djc — APPROVED** [review]

**Comment by yarikoptic** [comment]
anyways -- there is seems to be more todo since on windows
```
At D:\a\_temp\95c98458-1671-4858-9895-8f3f1274ea57.ps1:3 char:1
+ pip install flake8 coverage coveralls rply
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[DBG]: PS D:\a\rnc2rng\rnc2rng>> 
Error: The operation was canceled.
```
although similarly (but in different spots) it gets canceled on ubuntu as well etc... not entirely sure why - may be because other runs failed (due to failing to submit to coveralls).

I guess we could figure out if merged ;)

**Comment by djc** [comment]
I added Windows CI in #35.

**Comment by yarikoptic** [comment]
awesome, thank you.  IMHO it is a bit suboptimal happen you have some windows/python-version specific code paths, but better than nothing ;) 
also I would have kept 3.6 tested since AFAIK 3.6 is still supported and it could be quite a surprise if rnc2rng starts to fail on it.

**Comment by djc** [comment]
Feel free to add it back -- I don't keep up so well with the Python world these days.

**Pull request closed without merging**
